services:
  backend:
    build:
      context: ./app/backend
      dockerfile: ../../dockerfile/dockerfile_backend
    ports:
      - "5000:5000"
      
  frontend:
    build:
      context: ./app/frontend
      dockerfile: ../../dockerfile/dockerfile_frontend
    ports:
      - "8000:8000"

  tts:
    build:
      context: ./app/tts
      dockerfile: ../../dockerfile/dockerfile_tts
    ports:
      - "6000:6000"