# Image officielle Python 3.10 légère
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement requirements.txt pour utiliser le cache Docker sur l'installation pip
#COPY requirements.txt .

# Installer les dépendances
#RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code source
COPY . .

# Exposer le port de l'application (ex: 5000 pour Flask)
EXPOSE 6000

# Commande pour lancer ton app (à adapter)
CMD ["python", "index.html"]