# Image officielle Python 3.10 légère
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le reste du code source
COPY . .

# Installation des dépendances
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Exposer le port de l'application (ex: 5000 pour Flask)
EXPOSE 5000

# Commande pour lancer ton app (à adapter)
CMD ["python", "main.py"]